import { successResponse } from "@/lib/utils/api-response";

export const runtime = "nodejs";

// Built-in templates — no DB needed for defaults
const TEMPLATES = [
  {
    id: "honeymoon",
    slug: "honeymoon",
    name: "Romantic Honeymoon",
    description: "A dreamy escape for two — luxury stays, candlelit dinners, and unforgettable sunsets.",
    category: "honeymoon",
    coverImage: "https://images.unsplash.com/photo-1499678329028-101435549a4e?w=800&auto=format&fit=crop",
    durationDays: 7,
    estimatedBudget: 4000,
    currency: "USD",
    tags: ["romantic", "luxury", "couple"],
    travelStyle: "luxury",
    interests: ["food", "culture", "relaxation"],
  },
  {
    id: "solo-backpacker",
    slug: "solo-backpacker",
    name: "Solo Backpacking",
    description: "Travel light, meet locals, explore hidden gems on a shoestring budget.",
    category: "solo",
    coverImage: "https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=800&auto=format&fit=crop",
    durationDays: 10,
    estimatedBudget: 800,
    currency: "USD",
    tags: ["solo", "budget", "adventure"],
    travelStyle: "budget",
    interests: ["hiking", "culture", "local food"],
  },
  {
    id: "luxury-escape",
    slug: "luxury-escape",
    name: "Luxury Escape",
    description: "5-star hotels, Michelin-starred restaurants, private tours and VIP experiences.",
    category: "luxury",
    coverImage: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&auto=format&fit=crop",
    durationDays: 7,
    estimatedBudget: 8000,
    currency: "USD",
    tags: ["luxury", "premium", "relaxation"],
    travelStyle: "luxury",
    interests: ["spa", "fine dining", "culture"],
  },
  {
    id: "family-fun",
    slug: "family-fun",
    name: "Family Adventure",
    description: "Kid-friendly activities, theme parks, and memories the whole family will cherish.",
    category: "family",
    coverImage: "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800&auto=format&fit=crop",
    durationDays: 7,
    estimatedBudget: 3500,
    currency: "USD",
    tags: ["family", "kids", "fun"],
    travelStyle: "family",
    interests: ["theme parks", "nature", "food"],
  },
  {
    id: "road-trip",
    slug: "road-trip",
    name: "Epic Road Trip",
    description: "Windows down, playlist on — discover scenic routes, roadside diners, and hidden towns.",
    category: "roadtrip",
    coverImage: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&auto=format&fit=crop",
    durationDays: 10,
    estimatedBudget: 2000,
    currency: "USD",
    tags: ["roadtrip", "driving", "scenic"],
    travelStyle: "adventure",
    interests: ["nature", "photography", "local food"],
  },
  {
    id: "adventure-seeker",
    slug: "adventure-seeker",
    name: "Adventure Seeker",
    description: "Hiking, rafting, zip-lining, and adrenaline-fueled experiences in the wild.",
    category: "adventure",
    coverImage: "https://images.unsplash.com/photo-1526772662000-3f88f10405ff?w=800&auto=format&fit=crop",
    durationDays: 8,
    estimatedBudget: 2500,
    currency: "USD",
    tags: ["adventure", "outdoor", "extreme"],
    travelStyle: "adventure",
    interests: ["hiking", "extreme sports", "nature"],
  },
  {
    id: "cultural-immersion",
    slug: "cultural-immersion",
    name: "Cultural Immersion",
    description: "Museums, festivals, local cuisine, and deep dives into the history of your destination.",
    category: "cultural",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&auto=format&fit=crop",
    durationDays: 7,
    estimatedBudget: 2000,
    currency: "USD",
    tags: ["culture", "history", "art"],
    travelStyle: "cultural",
    interests: ["history", "museums", "local food"],
  },
  {
    id: "wellness-retreat",
    slug: "wellness-retreat",
    name: "Wellness Retreat",
    description: "Yoga, meditation, spa treatments, and holistic experiences for mind and body.",
    category: "wellness",
    coverImage: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop",
    durationDays: 7,
    estimatedBudget: 3000,
    currency: "USD",
    tags: ["wellness", "spa", "mindfulness"],
    travelStyle: "relaxation",
    interests: ["yoga", "spa", "nature"],
  },
];

export async function GET() {
  return successResponse({ templates: TEMPLATES });
}
